"""Scribe rendering engine — pure functions, no I/O."""

from __future__ import annotations

import html
import re
from datetime import UTC, datetime

# ── Proofread / recheck ──────────────────────────────────────────────────────

_PROOFREAD_SYSTEM = (
    "You are a meticulous DFIR report editor. You output ONLY the corrected text, "
    "nothing else — no preamble, no commentary."
)


def proofread(text: str, llm_call) -> str:
    """Recheck a report section to remove errors that slipped through.

    `llm_call(system, user) -> str` is injected by the caller (Scribe stays
    IO-free). The editor only CLEANS — it must not invent facts/IOCs/verdicts —
    so a failed/empty call falls back to the original text unchanged.
    """
    if not text or not text.strip() or llm_call is None:
        return text
    try:
        prompt = (
            "Proofread this investigation-report section. FIX ONLY: broken or "
            "half-rendered markdown/tables, duplicated or contradictory lines, "
            "dangling/empty references, malformed timestamps, and claims that "
            "contradict each other within the text. DO NOT add new facts, IPs, "
            "hostnames, CVEs or conclusions, and DO NOT remove real findings, "
            "fo_ids or IOCs. Preserve the structure and headings. If it's already "
            "clean, return it unchanged. Return ONLY the corrected text.\n\n"
            "----- BEGIN -----\n" + text + "\n----- END -----"
        )
        out = llm_call(_PROOFREAD_SYSTEM, prompt)
        out = (out or "").strip()
        # Guard against the model echoing the delimiters or refusing.
        for marker in ("----- BEGIN -----", "----- END -----"):
            out = out.replace(marker, "").strip()
        return out if out else text
    except Exception:
        return text

# ── Template ─────────────────────────────────────────────────────────────────

TEMPLATE_DEFAULTS = {
    "title_prefix": "Investigation report",
    "header_md": "",
    "footer_md": "_Generated by Citadel_",
    "max_flagged": 50,
    "sections": {
        "exec_summary": True,
        "overview": True,   # NEW — graphical aggregates
        "ai_report": True,
        "pinned": True,
        "flagged": True,
        "mitre": True,
        "detections": True,
        "watchlist": True,
        "notes": True,
    },
}


def merge_template(stored: dict | None) -> dict:
    """Stored template merged over defaults — missing keys fall back."""
    tpl = dict(TEMPLATE_DEFAULTS)
    tpl["sections"] = dict(TEMPLATE_DEFAULTS["sections"])
    if not isinstance(stored, dict):
        return tpl
    for k in ("title_prefix", "header_md", "footer_md"):
        if isinstance(stored.get(k), str):
            tpl[k] = stored[k]
    if isinstance(stored.get("max_flagged"), int) and stored["max_flagged"] > 0:
        tpl["max_flagged"] = min(stored["max_flagged"], 500)
    for k, v in (stored.get("sections") or {}).items():
        if k in tpl["sections"]:
            tpl["sections"][k] = bool(v)
    return tpl


# ── Shared helpers ───────────────────────────────────────────────────────────


def _ts(s: str) -> str:
    if not s:
        return ""
    try:
        return datetime.fromisoformat(str(s).replace("Z", "+00:00")).strftime(
            "%Y-%m-%d %H:%M:%S UTC"
        )
    except Exception:
        return str(s)


def _now() -> str:
    return _ts(datetime.now(UTC).isoformat())


def _ev_fields(ev: dict) -> dict:
    return {
        "ts": _ts(ev.get("timestamp", "")),
        "type": ev.get("artifact_type", "?"),
        "host": (ev.get("host") or {}).get("hostname", "") or "",
        "user": (ev.get("user") or {}).get("name", "") or "",
        "msg": (ev.get("message") or "").strip().splitlines()[0][:300] if ev.get("message") else "",
        "note": ev.get("pin_note", "") or "",
    }


# ════════════════════════════ MARKDOWN ════════════════════════════════════════


def _event_line(ev: dict) -> str:
    f = _ev_fields(ev)
    bits = [f"`{f['ts']}`" if f["ts"] else "", f"**{f['type']}**"]
    if f["host"]:
        bits.append(f"@ `{f['host']}`")
    if f["user"]:
        bits.append(f"user `{f['user']}`")
    if f["msg"]:
        bits.append(f"— {f['msg']}")
    return " ".join(b for b in bits if b)


def _agg_rows_md(title: str, items: list[dict], unit: str = "events") -> list[str]:
    if not items:
        return []
    out = [f"### {title}", ""]
    for it in items[:15]:
        out.append(f"- `{it.get('value')}` — {int(it.get('count', 0)):,} {unit}")
    out.append("")
    return out


def render_markdown(data: dict, tpl: dict | None = None) -> str:
    tpl = tpl or dict(TEMPLATE_DEFAULTS)
    sections = tpl.get("sections") or {}
    case = data.get("case") or {}
    pinned = data.get("pinned") or []
    flagged = data.get("flagged") or []
    mitre = data.get("mitre") or {}
    wl = data.get("watchlist") or {}
    det = data.get("detections") or {}
    notes = data.get("notes") or ""
    ai_report = data.get("ai_report")
    agg = data.get("aggregates") or {}

    out: list[str] = []
    name = case.get("name", case.get("case_id", "Case"))
    out.append(f"# {tpl.get('title_prefix') or 'Investigation report'} — {name}")
    out.append("")
    if (tpl.get("header_md") or "").strip():
        out.append(tpl["header_md"].strip())
        out.append("")
    out.append(f"_Generated {_now()}_")
    if case.get("company"):
        out.append(f"_Company: {case['company']}_")
    out.append("")

    if sections.get("exec_summary", True):
        out.append("## Executive summary")
        out.append("")
        if agg.get("total_events"):
            out.append(f"- **{int(agg['total_events']):,} total events** in scope.")
        out.append(f"- **{len(pinned)} pinned event(s)** curated as key evidence.")
        out.append(f"- **{len(flagged)} flagged event(s)** under analyst review.")
        out.append(f"- **{len(mitre.get('techniques', []))} MITRE ATT&CK techniques** evidenced.")
        if wl.get("hits"):
            out.append(f"- **{len(wl['hits'])} IOC watchlist hit(s)** in the latest sweep.")
        if det.get("matches"):
            out.append(f"- **{len(det['matches'])} detection rule(s)** fired.")
        out.append("")

    if sections.get("overview", True) and agg:
        out.append("## Activity overview")
        out.append("")
        out += _agg_rows_md("Artifact types", agg.get("artifact_types") or [])
        out += _agg_rows_md("Top source IPs", agg.get("top_src_ips") or [], "events")
        out += _agg_rows_md("Threat-intel matches", agg.get("cti") or [], "hits")

    if sections.get("ai_report", True) and ai_report and (ai_report.get("content") or "").strip():
        out.append("---")
        out.append("")
        out.append("## AI Autopilot investigation")
        out.append("")
        meta_bits = []
        if ai_report.get("generated_at"):
            meta_bits.append(f"_generated {_ts(ai_report['generated_at'])}_")
        if ai_report.get("model_used"):
            meta_bits.append(f"_{ai_report['model_used']}_")
        if meta_bits:
            out.append(" · ".join(meta_bits))
            out.append("")
        ai_content = (ai_report["content"] or "").strip()
        ai_content = "\n".join(
            ("##" + ln[1:]) if ln.startswith("# ") else ln for ln in ai_content.splitlines()
        )
        out.append(ai_content)
        out.append("")

    if sections.get("pinned", True) and pinned:
        out.append("## Key evidence (pinned events)")
        out.append("")
        for ev in pinned:
            out.append(f"- {_event_line(ev)}")
            if ev.get("pin_note"):
                out.append(f"  > _{ev['pin_note']}_")
        out.append("")

    max_flagged = int(tpl.get("max_flagged") or 50)
    if sections.get("flagged", True) and flagged:
        out.append("## Flagged events")
        out.append("")
        for ev in flagged[:max_flagged]:
            out.append(f"- {_event_line(ev)}")
        if len(flagged) > max_flagged:
            out.append(f"_…and {len(flagged) - max_flagged} more._")
        out.append("")

    techs = mitre.get("techniques", []) if sections.get("mitre", True) else []
    if techs:
        out.append("## MITRE ATT&CK coverage")
        out.append("")
        by_tactic: dict[str, list] = {}
        for t in techs:
            by_tactic.setdefault(t.get("tactic") or "Unknown", []).append(t)
        for tactic, items in sorted(by_tactic.items()):
            out.append(f"### {tactic}")
            for t in sorted(items, key=lambda x: -x.get("count", 0)):
                out.append(f"- `{t['id']}` {t.get('name', '')} — {t.get('count', 0)} event(s)")
            out.append("")

    if sections.get("detections", True) and det.get("matches"):
        out.append("## Detection rules that fired")
        out.append("")
        out.append(f"_Last run: {_ts(det.get('ran_at', ''))}_")
        for m in det["matches"]:
            rule = m.get("rule") or {}
            out.append(f"- **{rule.get('name', '?')}** ({m.get('match_count', 0)} match(es))")
            if rule.get("description"):
                out.append(f"  > {rule['description']}")
        out.append("")

    if sections.get("watchlist", True) and wl.get("hits"):
        out.append("## IOC watchlist hits")
        out.append("")
        out.append(f"_Auto-sweep: {_ts(wl.get('ran_at', ''))}_")
        for h in wl["hits"]:
            out.append(f"- **{h.get('label')}** (`{h.get('kind')}`) — {h.get('hits')} match(es)")
            out.append(f"  - Query: `{h.get('query')}`")
        out.append("")

    if sections.get("notes", True) and notes:
        out.append("## Analyst notes")
        out.append("")
        out.append(notes)
        out.append("")

    out.append("---")
    if (tpl.get("footer_md") or "").strip():
        out.append(tpl["footer_md"].strip())
    return "\n".join(out)


# ════════════════════════════ HTML (graphical) ════════════════════════════════


def _e(s) -> str:
    return html.escape(str(s if s is not None else ""))


def _inline_html(s: str) -> str:
    """Inline markdown marks on already-escaped text."""
    s = html.escape(s)
    s = re.sub(r"`([^`]+)`", r"<code>\1</code>", s)
    s = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", s)
    s = re.sub(r"(?<!\w)_([^_]+)_(?!\w)", r"<em>\1</em>", s)
    s = re.sub(r"\[([^\]]+)\]\((https?://[^)]+)\)", r'<a href="\2">\1</a>', s)
    return s


def _md_to_html(md: str) -> str:
    """Small Markdown → HTML for free-text blocks (AI report, notes). Handles
    headings, lists, blockquotes, hr, inline marks AND pipe tables (the bit the
    old renderer dropped — markdown tables came out as literal `| a | b |`)."""
    lines = md.splitlines()
    out: list[str] = []
    in_list = False
    i = 0

    def _close_list():
        nonlocal in_list
        if in_list:
            out.append("</ul>")
            in_list = False

    while i < len(lines):
        line = lines[i].rstrip()
        # Pipe table: a header row followed by a |---|---| separator.
        if (
            line.lstrip().startswith("|")
            and i + 1 < len(lines)
            and re.match(r"^\s*\|?[\s:|-]+\|?\s*$", lines[i + 1])
            and "-" in lines[i + 1]
        ):
            _close_list()
            def _cells(row):
                row = row.strip().strip("|")
                return [c.strip() for c in row.split("|")]
            headers = _cells(line)
            out.append('<table><thead><tr>')
            out.extend(f"<th>{_inline_html(h)}</th>" for h in headers)
            out.append("</tr></thead><tbody>")
            i += 2
            while i < len(lines) and lines[i].lstrip().startswith("|"):
                cells = _cells(lines[i])
                out.append("<tr>" + "".join(f"<td>{_inline_html(c)}</td>" for c in cells) + "</tr>")
                i += 1
            out.append("</tbody></table>")
            continue
        if not line:
            _close_list()
            out.append("")
            i += 1
            continue
        for lvl, prefix in ((1, "# "), (2, "## "), (3, "### "), (4, "#### ")):
            if line.startswith(prefix):
                _close_list()
                out.append(f"<h{lvl}>{_inline_html(line[len(prefix):])}</h{lvl}>")
                break
        else:
            if line == "---":
                _close_list()
                out.append("<hr/>")
            elif line.startswith("  > ") or line.startswith("> "):
                _close_list()
                txt = line.split(">", 1)[1].strip()
                out.append(f"<blockquote>{_inline_html(txt)}</blockquote>")
            elif line.lstrip().startswith("- "):
                if not in_list:
                    out.append("<ul>")
                    in_list = True
                out.append(f"<li>{_inline_html(line.lstrip()[2:])}</li>")
            else:
                _close_list()
                out.append(f"<p>{_inline_html(line)}</p>")
        i += 1
    _close_list()
    return "\n".join(out)


def _stat_cards(cards: list[tuple[str, object]]) -> str:
    cells = "".join(
        f'<div class="card"><div class="num">{_e(v)}</div><div class="lbl">{_e(l)}</div></div>'
        for l, v in cards
    )
    return f'<div class="cards">{cells}</div>'


def _bar_chart(items: list[dict], unit: str = "") -> str:
    """Horizontal CSS bars for an aggregate (value/count list)."""
    items = [it for it in (items or []) if it.get("value") not in (None, "")][:12]
    if not items:
        return ""
    mx = max(int(it.get("count", 0)) for it in items) or 1
    rows = []
    for it in items:
        c = int(it.get("count", 0))
        pct = max(2, round(c / mx * 100))
        rows.append(
            f'<div class="bar-row"><span class="bar-lbl" title="{_e(it["value"])}">{_e(it["value"])}</span>'
            f'<span class="bar-track"><span class="bar-fill" style="width:{pct}%"></span></span>'
            f'<span class="bar-val">{c:,}{(" " + unit) if unit else ""}</span></div>'
        )
    return f'<div class="bars">{"".join(rows)}</div>'


def _event_table(events: list[dict], cap: int) -> str:
    rows = []
    for ev in events[:cap]:
        f = _ev_fields(ev)
        rows.append(
            "<tr>"
            f"<td class=mono>{_e(f['ts'])}</td>"
            f"<td><span class=tag>{_e(f['type'])}</span></td>"
            f"<td class=mono>{_e(f['host'])}</td>"
            f"<td class=mono>{_e(f['user'])}</td>"
            f"<td>{_e(f['msg'])}{('<div class=note>' + _e(f['note']) + '</div>') if f['note'] else ''}</td>"
            "</tr>"
        )
    extra = f'<div class="muted">…and {len(events) - cap} more.</div>' if len(events) > cap else ""
    return (
        "<table class=evt><thead><tr><th>Time</th><th>Type</th><th>Host</th>"
        "<th>User</th><th>Message</th></tr></thead><tbody>"
        + "".join(rows)
        + "</tbody></table>"
        + extra
    )


_HTML_CSS = """
:root{--ink:#0F172A;--mut:#64748B;--line:#E5E7EB;--accent:#6366F1;--bg:#fff;}
*{box-sizing:border-box}
body{font:14px/1.55 -apple-system,BlinkMacSystemFont,'Segoe UI',Inter,sans-serif;color:var(--ink);max-width:980px;margin:2em auto;padding:0 1.2em;background:var(--bg);}
h1{font-size:1.9em;letter-spacing:-.02em;border-bottom:1px solid var(--line);padding-bottom:.4em;}
h2{font-size:1.3em;margin-top:2em;letter-spacing:-.01em;}
h3{font-size:1.05em;color:#4B5563;margin:1.2em 0 .4em;}
h4{font-size:.98em;color:#4B5563;}
.meta{color:var(--mut);font-size:.9em;}
code{background:#F3F4F6;padding:.1em .35em;border-radius:3px;font-family:'JetBrains Mono',Consolas,monospace;font-size:.9em;}
.mono{font-family:'JetBrains Mono',Consolas,monospace;font-size:.85em;color:#334155;white-space:nowrap;}
blockquote{border-left:3px solid var(--accent);margin:.5em 0;padding:.2em 1em;color:#4B5563;background:#F9FAFB;}
hr{border:none;border-top:1px solid var(--line);margin:2em 0;}
.cards{display:flex;flex-wrap:wrap;gap:.7em;margin:1em 0;}
.card{flex:1 1 120px;border:1px solid var(--line);border-radius:10px;padding:.8em 1em;background:#FAFAFB;}
.card .num{font-size:1.5em;font-weight:700;color:var(--accent);}
.card .lbl{font-size:.78em;color:var(--mut);margin-top:.2em;text-transform:uppercase;letter-spacing:.03em;}
.bars{margin:.4em 0 1.2em;}
.bar-row{display:flex;align-items:center;gap:.6em;margin:.18em 0;font-size:.85em;}
.bar-lbl{width:200px;flex-shrink:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-family:'JetBrains Mono',monospace;color:#334155;}
.bar-track{flex:1;background:#F1F5F9;border-radius:4px;height:14px;overflow:hidden;}
.bar-fill{display:block;height:100%;background:linear-gradient(90deg,#818CF8,#6366F1);}
.bar-val{width:96px;flex-shrink:0;text-align:right;color:var(--mut);font-variant-numeric:tabular-nums;}
table{border-collapse:collapse;width:100%;margin:.6em 0 1.4em;font-size:.86em;}
th,td{border:1px solid var(--line);padding:.4em .6em;text-align:left;vertical-align:top;}
th{background:#F8FAFC;font-weight:600;color:#334155;}
tr:nth-child(even) td{background:#FCFCFD;}
table.evt td:last-child{white-space:normal;}
.tag{background:#EEF2FF;color:#4338CA;border-radius:4px;padding:.05em .45em;font-size:.85em;}
.note{color:var(--mut);font-style:italic;font-size:.92em;margin-top:.2em;}
.muted{color:var(--mut);font-size:.85em;margin:.3em 0;}
@media print{body{max-width:100%;margin:0;}.card{background:#fff;}}
"""


def render_html(data: dict, tpl: dict | None = None) -> str:
    tpl = tpl or dict(TEMPLATE_DEFAULTS)
    sections = tpl.get("sections") or {}
    case = data.get("case") or {}
    pinned = data.get("pinned") or []
    flagged = data.get("flagged") or []
    mitre = data.get("mitre") or {}
    wl = data.get("watchlist") or {}
    det = data.get("detections") or {}
    notes = data.get("notes") or ""
    ai_report = data.get("ai_report")
    agg = data.get("aggregates") or {}
    name = case.get("name", case.get("case_id", "Case"))
    max_flagged = int(tpl.get("max_flagged") or 50)

    b: list[str] = []
    b.append(f"<h1>{_e(tpl.get('title_prefix') or 'Investigation report')} — {_e(name)}</h1>")
    if (tpl.get("header_md") or "").strip():
        b.append(_md_to_html(tpl["header_md"].strip()))
    meta = [f"Generated {_e(_now())}"]
    if case.get("company"):
        meta.append(f"Company: {_e(case['company'])}")
    b.append(f'<p class="meta">{" · ".join(meta)}</p>')

    if sections.get("exec_summary", True):
        b.append("<h2>Executive summary</h2>")
        cards = []
        if agg.get("total_events"):
            cards.append(("Events", f"{int(agg['total_events']):,}"))
        cards += [
            ("Pinned", len(pinned)),
            ("Flagged", len(flagged)),
            ("MITRE techniques", len(mitre.get("techniques", []))),
        ]
        if wl.get("hits"):
            cards.append(("Watchlist hits", len(wl["hits"])))
        if det.get("matches"):
            cards.append(("Detections", len(det["matches"])))
        b.append(_stat_cards(cards))

    if sections.get("overview", True) and agg:
        b.append("<h2>Activity overview</h2>")
        if agg.get("artifact_types"):
            b.append("<h3>Artifact types</h3>")
            b.append(_bar_chart(agg["artifact_types"]))
        if agg.get("top_src_ips"):
            b.append("<h3>Top source IPs</h3>")
            b.append(_bar_chart(agg["top_src_ips"], "events"))
        if agg.get("severity"):
            b.append("<h3>Severity</h3>")
            b.append(_bar_chart(agg["severity"]))
        if agg.get("cti"):
            b.append("<h3>Threat-intel matches</h3>")
            b.append(_bar_chart(agg["cti"], "hits"))

    if sections.get("ai_report", True) and ai_report and (ai_report.get("content") or "").strip():
        b.append("<hr/><h2>AI Autopilot investigation</h2>")
        mb = []
        if ai_report.get("generated_at"):
            mb.append(f"generated {_e(_ts(ai_report['generated_at']))}")
        if ai_report.get("model_used"):
            mb.append(_e(ai_report["model_used"]))
        if mb:
            b.append(f'<p class="meta">{" · ".join(mb)}</p>')
        ai_content = (ai_report["content"] or "").strip()
        ai_content = "\n".join(
            ("##" + ln[1:]) if ln.startswith("# ") else ln for ln in ai_content.splitlines()
        )
        b.append(_md_to_html(ai_content))

    if sections.get("pinned", True) and pinned:
        b.append("<h2>Key evidence (pinned events)</h2>")
        b.append(_event_table(pinned, 500))

    if sections.get("flagged", True) and flagged:
        b.append("<h2>Flagged events</h2>")
        b.append(_event_table(flagged, max_flagged))

    techs = mitre.get("techniques", []) if sections.get("mitre", True) else []
    if techs:
        b.append("<h2>MITRE ATT&CK coverage</h2>")
        by_tactic: dict[str, list] = {}
        for t in techs:
            by_tactic.setdefault(t.get("tactic") or "Unknown", []).append(t)
        for tactic, items in sorted(by_tactic.items()):
            b.append(f"<h3>{_e(tactic)}</h3>")
            b.append(
                _bar_chart(
                    [{"value": f"{t['id']} {t.get('name', '')}".strip(), "count": t.get("count", 0)}
                     for t in sorted(items, key=lambda x: -x.get("count", 0))]
                )
            )

    if sections.get("detections", True) and det.get("matches"):
        b.append("<h2>Detection rules that fired</h2>")
        b.append(f'<p class="meta">Last run: {_e(_ts(det.get("ran_at", "")))}</p>')
        rows = "".join(
            f"<tr><td>{_e((m.get('rule') or {}).get('name', '?'))}</td>"
            f"<td>{_e(m.get('match_count', 0))}</td>"
            f"<td>{_e((m.get('rule') or {}).get('description', ''))}</td></tr>"
            for m in det["matches"]
        )
        b.append(f"<table><thead><tr><th>Rule</th><th>Matches</th><th>Description</th></tr></thead><tbody>{rows}</tbody></table>")

    if sections.get("watchlist", True) and wl.get("hits"):
        b.append("<h2>IOC watchlist hits</h2>")
        b.append(f'<p class="meta">Auto-sweep: {_e(_ts(wl.get("ran_at", "")))}</p>')
        rows = "".join(
            f"<tr><td>{_e(h.get('label'))}</td><td><span class=tag>{_e(h.get('kind'))}</span></td>"
            f"<td>{_e(h.get('hits'))}</td><td class=mono>{_e(h.get('query'))}</td></tr>"
            for h in wl["hits"]
        )
        b.append(f"<table><thead><tr><th>Label</th><th>Kind</th><th>Hits</th><th>Query</th></tr></thead><tbody>{rows}</tbody></table>")

    if sections.get("notes", True) and notes:
        b.append("<h2>Analyst notes</h2>")
        b.append(_md_to_html(notes))

    b.append("<hr/>")
    if (tpl.get("footer_md") or "").strip():
        b.append(f'<p class="meta">{_md_to_html(tpl["footer_md"].strip())}</p>')

    return (
        "<!doctype html><html><head><meta charset=utf-8/>"
        f"<title>{_e(name)} — Citadel report</title><style>{_HTML_CSS}</style>"
        f"</head><body>{''.join(b)}</body></html>"
    )
